#!/bin/bash

# 检查是否提供了两个文件作为参数
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 src.json dest.json"
  exit 1
fi

src_file="$1"
dest_file="$2"

# 检查文件是否存在
if [ ! -f "$src_file" ] || [ ! -f "$dest_file" ]; then
  echo "Error: One or both files do not exist."
  exit 1
fi

# 获取 src 文件中的所有 key
keys=$(jq -r 'keys[]' "$src_file")

# 假设两个 JSON 文件的 key 是相同的，所以取 src 文件的 key 就够了
# 循环比较每个 key 对应的 value
versions_consistent=true
IFS=$'\n' read -r -a key_arr <<< "$keys"
for key in "${key_arr[@]}"; do
  src_value=$(jq -r ".\"${key}\"" "$src_file")
  dest_value=$(jq -r ".\"${key}\"" "$dest_file")

  if [[ "$src_value" != "$dest_value" ]]; then
    versions_consistent=false
    break
  fi
done

if [[ "$versions_consistent" == "true" ]]; then
    exit 0
else
    exit 1
fi