name: Products Release Notes PR
defaults:
  run:
    shell: bash
env:
  SSH_GIT_REPO: ${{ secrets.SSH_GIT_REPO }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
  PUBLISH_VERSION: ${{ inputs.PUBLISH_VERSION || vars.PUBLISH_VERSION }}
  
on:
  workflow_dispatch:
    inputs:
      OPERATION:
        description: 'Create PR/Tag'
        required: true
        type: choice
        options: ['PR', 'Tag', "PPR"]
        default: "PR"
      PUBLISH_VERSION:
        description: 'Publish Version'
        required: false
        default: ""
      PUBLISH_FRAMEWORK_VERSION:
        description: 'Publish Framework Version'
        required: false
        default: "" 
      PUBLISH_EZS_VERSION:
        description: 'Publish Easysearch Version'
        required: false
        default: ""
      AGENT_PUBLISH:
        description: 'Agent'
        required: false
        type: boolean
        default: true
      CONSOLE_PUBLISH:
        description: 'Console'
        required: false
        type: boolean
        default: true
      GATEWAY_PUBLISH:
        description: 'Gateway'
        required: false
        type: boolean
        default: true
      LOADGEN_PUBLISH:
        description: 'Loadgen'
        required: false
        type: boolean
        default: true
      FRAMEWORK_PUBLISH:
        description: 'Framework'
        required: false
        type: boolean
        default: true
      EASYSEARCH_PUBLISH:
        description: 'Easysearch'
        required: false
        type: boolean
        default: true

jobs:
  generate-matrix: 
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate matrix
        id: gen-matrix
        env:
            AGENT_PUBLISH: ${{ inputs.AGENT_PUBLISH }}
            CONSOLE_PUBLISH: ${{ inputs.CONSOLE_PUBLISH }}
            GATEWAY_PUBLISH: ${{ inputs.GATEWAY_PUBLISH }}
            LOADGEN_PUBLISH: ${{ inputs.LOADGEN_PUBLISH }}
            FRAMEWORK_PUBLISH: ${{ inputs.FRAMEWORk_PUBLISH }}
            EASYSEARCH_PUBLISH: ${{ inputs.EASYSEARCH_PUBLISH }}
        run: |
          matrix=$($GITHUB_WORKSPACE/scripts/go-matrix.sh)
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  publish:
    needs: generate-matrix
    name: Create ${{ inputs.OPERATION }} for ${{ matrix.product }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up and check env for ${{ matrix.product }}
        run: |
          $GITHUB_WORKSPACE/scripts/env-init.sh
          if [[ "${{ matrix.product }}" == "framework" ]]; then
            VERSION=${{ inputs.PUBLISH_FRAMEWORK_VERSION }}
            if [[ -z "$VERSION" ]]; then
              echo "Please input the framework version"
              exit 1
            fi
          elif [[ "${{ matrix.product }}" == "easysearch" ]]; then
            VERSION=${{ inputs.PUBLISH_EZS_VERSION }}
            if [[ -z "$VERSION" ]]; then
              echo "Please input the easysearch version"
              exit 1
            fi
          else
            VERSION=$(echo "${{ env.PUBLISH_VERSION }}" | sed 's/-.*//')
          fi
          
          if [[ "${{ inputs.OPERATION }}" == "PPR" ]]; then
            PR_BRANCH=release_for_next
            PR_MESSAGE="chore: update release notes template for next publish"
          else
            PR_BRANCH="release_$VERSION"
            PR_MESSAGE="chore: update release notes for publish $VERSION"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
          echo "PR_MESSAGE=$PR_MESSAGE" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Checkout ${{ matrix.product }} code
        run: |
          if [[ "${{ matrix.product }}" == "easysearch" ]]; then
            git clone $SSH_GIT_REPO/${{ matrix.product }} $GITHUB_WORKSPACE/${{ matrix.product }}
          else
            git clone ${{ vars.GIT_SSH_REPO }}/${{ matrix.product }} $GITHUB_WORKSPACE/${{ matrix.product }}
          fi
     
      - name: Check tag and create tag for ${{ matrix.product }}
        if: ${{ inputs.OPERATION == 'Tag'}}
        run: |
          cd $GITHUB_WORKSPACE/${{ matrix.product }}
          echo "Check tag and create tag for ${{ matrix.product }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          tag_exists=$(git rev-parse --verify "refs/tags/$VERSION" 2>/dev/null && echo true || echo false)
          if [ "$tag_exists" == "false" ]; then
            git tag -a $VERSION -m "Release $VERSION"
            git push origin $VERSION
          fi

      - name: Create Branch for ${{ matrix.product }}
        if: ${{ inputs.OPERATION == 'PR' && matrix.product != 'easysearch' }}
        run: |
          cd $GITHUB_WORKSPACE/${{ matrix.product }}
          echo "Create Branch $PR_BRANCH for ${{ matrix.product }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "$PR_BRANCH"
          #update release notes
          PUBLISH="$(echo "$VERSION" | sed 's/-.*//') ($(date +'%Y-%m-%d'))"
          for f in en zh; do
            if [[ "${{ matrix.product }}" == "framework" ]] && [[ "$f" == "zh" ]]; then
              continue
            fi
            sed -i "s/## Latest.*/## $PUBLISH/" docs/content.$f/docs/release-notes/_index.md
            if [[ "${{ inputs.OPERATION }}" == "PPR" ]]; then
              sed -i -e "/^## $PUBLISH/i ## Latest (In development)  \\n### Breaking changes  \\n### Features  \\n### Bug fix  \\n### Improvements  \\n" docs/content.$f/docs/release-notes/_index.md
            fi
            git add docs/content.$f/docs/release-notes/_index.md
          done

      - name: Create Commit Message for ${{ matrix.product }}
        if: ${{ inputs.OPERATION == 'PR' && matrix.product != 'easysearch' }}
        run: |
          cd $GITHUB_WORKSPACE/${{ matrix.product }}
          git commit -m "$PR_MESSAGE"     
          git push origin "$PR_BRANCH"

      - name: Create Github Pull Request for ${{ matrix.product }}
        env:
          GH_TOKEN: ${{ secrets.REPO_PAT }} 
        run: |
          cd $GITHUB_WORKSPACE/${{ matrix.product }}
          gh pr create --title "$PR_MESSAGE" \
                  --body "This PR updates the release notes." \
                  --base main \
                  --head "$PR_BRANCH"