name: Products Release Notes PR
defaults:
  run:
    shell: bash
env:
  SSH_GIT_REPO: ${{ secrets.SSH_GIT_REPO }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
  PUBLISH_VERSION: ${{ inputs.PUBLISH_VERSION || vars.PUBLISH_VERSION }}
  
on:
  schedule:
    - cron: '15 17 * * *'  
  workflow_dispatch:
    inputs:
      NEXT_PUBLISH:
        description: 'Next Template Release Notes'
        required: false
        type: boolean
        default: false        
      PUBLISH_VERSION:
        description: 'Publish Version'
        required: false
        default: ""
      PUBLISH_FRAMEWORK_VERSION:
        description: 'Publish Framework Version'
        required: false
        default: "" 
      AGENT_PUBLISH:
        description: 'Agent'
        required: false
        type: boolean
        default: true
      CONSOLE_PUBLISH:
        description: 'Console'
        required: false
        type: boolean
        default: true
      GATEWAY_PUBLISH:
        description: 'Gateway'
        required: false
        type: boolean
        default: true
      LOADGEN_PUBLISH:
        description: 'Loadgen'
        required: false
        type: boolean
        default: true
      FRAMEWORK_PUBLISH:
        description: 'Framework'
        required: false
        type: boolean
        default: true

jobs:
  generate-matrix: 
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate matrix
        id: gen-matrix
        env:
            AGENT_PUBLISH: ${{ inputs.AGENT_PUBLISH }}
            CONSOLE_PUBLISH: ${{ inputs.CONSOLE_PUBLISH }}
            GATEWAY_PUBLISH: ${{ inputs.GATEWAY_PUBLISH }}
            LOADGEN_PUBLISH: ${{ inputs.LOADGEN_PUBLISH }}
            FRAMEWORK_PUBLISH: ${{ inputs.FRAMEWORk_PUBLISH }}
        run: |
          matrix=$($GITHUB_WORKSPACE/scripts/go-matrix.sh)
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  publish:
    needs: generate-matrix
    name: Create ${{ matrix.product }} PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up and check env
        run: |
          $GITHUB_WORKSPACE/scripts/env-init.sh
          echo "VERSION=${{ env.PUBLISH_VERSION }}" >> $GITHUB_ENV
          if [[ "${{ inputs.NEXT_PUBLISH }}" == "true" ]]; then
            echo "PR_BRANCH=release_for_next" >> $GITHUB_ENV
            echo "PR_MESSAGE=chore: update release notes template for next publish" >> $GITHUB_ENV
          else
            echo "PR_BRANCH=release_${{ env.PUBLISH_VERSION }}" >> $GITHUB_ENV
            echo "PR_MESSAGE=chore: update release notes for publish ${{ env.PUBLISH_VERSION }}" >> $GITHUB_ENV
          fi

      - name: Checkout ${{ matrix.product }} code
        run: |
          git clone ${{ vars.GIT_SSH_REPO }}/${{ matrix.product }} $GITHUB_WORKSPACE/${{ matrix.product }}

      - name: Create Branch for ${{ matrix.product }}
        run: |
          if [[ "${{ matrix.product }}" == "framework" ]]; then
            VERSION=${{ inputs.PUBLISH_FRAMEWORK_VERSION }}
            if [[ -z "$VERSION" ]]; then
              echo "Please input the framework version"
              exit 1
            fi
          fi
          cd $GITHUB_WORKSPACE/${{ matrix.product }}
          echo "Create Branch $PR_BRANCH for ${{ matrix.product }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b "$PR_BRANCH"
          #update release notes
          for f in en zh; do
            sed -i "s/## Latest.*/## $(echo "$VERSION" | sed 's/-.*//') ($(date +'%Y-%m-%d'))/" docs/content.$f/docs/release-notes/_index.md
            if [[ "${{ inputs.NEXT_PUBLISH }}" == "true" ]]; then
              sed -i '/^## '"$(echo "${{ inputs.PUBLISH_VERSION }}" | sed 's/-.*//')"'\ ('"$(date +'%Y-%m-%d')"'\)$/i \
                ## Latest (In development)\
                \
                ### Breaking changes\
                \
                ### Features\
                \
                ### Bug fix\
                \
                ### Improvements\
                \' docs/content.$f/docs/release-notes/_index.md
            fi
            git add docs/content.$f/docs/release-notes/_index.md
          done

      - name: Create Commit Message for ${{ matrix.product }}
        run: |
          if [[ "${{ matrix.product }}" == "framework" ]]; then
            VERSION=${{ inputs.PUBLISH_FRAMEWORK_VERSION }}
            if [[ -z "$VERSION" ]]; then
              echo "Please input the framework version"
              exit 1
            fi
          fi
          cd $GITHUB_WORKSPACE/${{ matrix.product }}
          git commit -m "$PR_MESSAGE"     
          git push origin "$PR_BRANCH"

      - name: Create Github Pull Request for ${{ matrix.product }}
        env:
          GH_TOKEN: ${{ secrets.REPO_PAT }} 
        run: |
          if [[ "${{ matrix.product }}" == "framework" ]]; then
            VERSION=${{ inputs.PUBLISH_FRAMEWORK_VERSION }}
            if [[ -z "$VERSION" ]]; then
              echo "Please input the framework version"
              exit 1
            fi
          fi
          cd $GITHUB_WORKSPACE/${{ matrix.product }}
          gh pr create --title "$PR_MESSAGE" \
                  --body "This PR updates the release notes." \
                  --base main \
                  --head "$PR_BRANCH"
