name: Repackage Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v0.2.0'


jobs:
  repack:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Assets
        id: get_assets
        run: |
          ASSET_URLS=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/infinilabs/coco-app/releases/tags/${{ inputs.tag}} | \
            jq -r '.assets[].browser_download_url')
          echo "::set-output name=asset_urls::$ASSET_URLS"

      - name: Download Assets
        run: |
          IFS=$'\n'
          for url in "${{ steps.get_assets.outputs.asset_urls }}"; do
            curl -L -O "$url"
          done
          ls -lrt ./
        shell: bash