name: Test Github Actions

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:

jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
      - name: Set up and check env
        run: |
          echo $GITHUB_WORKSPACE
          env | sort
          touch $GITHUB_WORKSPACE/job1.txt
  job2:
    name: Job2
    runs-on: ubuntu-latest
    steps:
      - name: Set up and check env
        run: |
          echo $GITHUB_WORKSPACE
          env | sort
          ls -lrt $GITHUB_WORKSPACE

  job3:
    name: Job3
    runs-on: ubuntu-latest
    steps:
      - name: Set up and check env
        run: |
          ls -lrt /bin
          ls -lrt /sbin
          find / -name socat 2>/dev/null