


name: Test Timezone
defaults:
  run:
    shell: bash

env:
    PNAME: test2

on:
  workflow_dispatch:
    inputs:
      PUBLISH_VERSION:
        description: 'Publish version'
        required: true
        default: '0.2.2-NIGHTLY-20250316'
      PUBLISH_RELEASE:
        description: 'Publish release'
        required: true
        default: 'false'

jobs:
  build-app:
    env:
      PUBLISH_VERSION: ${{ vars.COCO_PUBLISH_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            target: "aarch64-apple-darwin"
          - platform: "macos-latest"
            target: "x86_64-apple-darwin"

          - platform: "windows-latest"
            target: "x86_64-pc-windows-msvc"
          - platform: "windows-latest"
            target: "i686-pc-windows-msvc"
          - platform: "windows-latest"
            target: "aarch64-pc-windows-msvc"

          - platform: "ubuntu-22.04"
            target: "x86_64-unknown-linux-gnu"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Tag with ${{ matrix.platform }}
        shell: bash
        run: |
          current_version=$PUBLISH_VERSION
          if [ -z "$current_version" ]; then
            echo "PUBLISH_VERSION is not set or is empty." >&2
            exit 1
          fi

          # Extract x.y.z using a regular expression
          if [[ "$current_version" =~ ^([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            current_version="${BASH_REMATCH[1]}"
          else
            echo "Invalid PUBLISH_VERSION format: '$current_version'. Expected x.y.z or x.y.z-suffix." >&2
            exit 1
          fi
          tag=".v${current_version}"
          echo "UPGRADE=$tag" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Set Version with ${{ matrix.platform }}
        if: ${{ !inputs.PUBLISH_RELEASE }}
        shell: bash
        run: |
          package_json="package.json"
          current_version=$PUBLISH_VERSION
          if [ -z "$current_version" ]; then
            echo "PUBLISH_VERSION is not set or is empty." >&2
            exit 1
          fi

          # Extract x.y.z using a regular expression
          if [[ "$current_version" =~ ^([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            current_version="${BASH_REMATCH[1]}"
          else
            echo "Invalid PUBLISH_VERSION format: '$current_version'. Expected x.y.z or x.y.z-suffix." >&2
            exit 1
          fi
          echo "Current version: $current_version"
          echo `date +%Y%m%d%H%M%S`
          date_str=$(TZ='Asia/Shanghai' date +%Y%m%d)
          IFS=. read -r major minor patch <<< "$current_version"
          new_version="$major.$minor.$((patch + 1))-NIGHTLY-${date_str}"
          if ${{ matrix.platform == 'macos-latest' }}; then
            sed -i '' "s/\"version\": *\"[^\"]*\"/\"version\": \"$new_version\"/" "$package_json"
          else
            sed -i -e "s/\"version\": *\"[^\"]*\"/\"version\": \"$new_version\"/" "$package_json"
          fi
          echo "Version updated to: $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV