name: Repackage Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v0.2.0'

env:
  GITHUB_API_RELEASES_URL: "https://api.github.com/repos/infinilabs/coco-app/releases"
  BASE_URL_PREFIX: "https://github.com/infinilabs/coco-app/releases/download"
  FILE_EXTENSIONS: '\.(dmg|deb|exe)$'

jobs:
  repack:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Asset Names
        id: get_assets
        run: |
          ASSET_NAMES=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            "$GITHUB_API_RELEASES_URL/tags/${{ inputs.tag }}" | \
            jq -r '.assets[].name')
          echo "$ASSET_NAMES" > asset_names.txt
          cat asset_names.txt

      - name: Download and Filter Assets
        run: |
          BASE_URL="$BASE_URL_PREFIX/${{ inputs.tag }}"

          grep -E -i "$FILE_EXTENSIONS" asset_names.txt | while read -r filename; do
            echo "Downloading $filename from $BASE_URL"
            url="$BASE_URL/$filename"
            curl -sSL -o "$filename" "$url"
          done

          ls -lrt ./
        shell: bash